# Generated by Django 5.2.15 on 2026-06-06 08:55

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_member_is_staff_member_is_superuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessgroup",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="member",
            name="group",
            field=models.ForeignKey(
                blank=True,
                default=accounts.models.get_default_group_id,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="members",
                to="accounts.accessgroup",
            ),
        ),
    ]
