# Generated by Django 5.2.15 on 2026-06-15 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_accessgroup_is_default_alter_member_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="deactivated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="deactivation_reason",
            field=models.TextField(blank=True),
        ),
    ]
