# Generated by Django 5.2.15 on 2026-06-18 16:33

import random

from django.db import migrations, models


def backfill_member_number(apps, schema_editor):
    Member = apps.get_model('accounts', 'Member')
    existing = set(Member.objects.exclude(member_number=None).values_list('member_number', flat=True))
    for member in Member.objects.filter(member_number=None):
        for _ in range(20):
            candidate = random.randint(10000, 99999)
            if candidate not in existing:
                existing.add(candidate)
                member.member_number = candidate
                member.save(update_fields=['member_number'])
                break
        else:
            raise RuntimeError('Could not generate a unique member number.')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_member_deactivated_by_member_deactivation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="member_number",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.RunPython(backfill_member_number, noop_reverse),
    ]
