# Generated by Django 5.2.15 on 2026-06-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_member_member_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="deactivation_reason",
            field=models.TextField(blank=True, max_length=550),
        ),
    ]
