# Generated by Django 5.2.15 on 2026-06-23 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwvault", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordVaultHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("key_version", models.PositiveSmallIntegerField()),
                ("dek_envelope", models.JSONField()),
                ("ciphertext_layers", models.JSONField()),
                ("chain_hash", models.CharField(max_length=64)),
                ("prev_chain_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_vault_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["member", "sequence"],
            },
        ),
        migrations.AddConstraint(
            model_name="passwordvaulthistory",
            constraint=models.UniqueConstraint(
                fields=("member", "sequence"), name="pwvault_history_unique_sequence"
            ),
        ),
    ]
