# Generated by Django 5.2.15 on 2026-06-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pwvault", "0004_remove_passwordvaultentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultKeyMaterial",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("nonce", models.TextField()),
                ("wrapped_pepper", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="passwordvaulthistory",
            name="classical_salt",
            field=models.TextField(blank=True, default=""),
        ),
    ]
