# Generated by Django 5.2.15 on 2026-06-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0002_alter_expense_withdrawn_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="receipt_image",
            field=models.ImageField(blank=True, upload_to="contribution_receipts/"),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("pending_review", "Pending Review"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
