# Generated by Django 5.2.15 on 2026-06-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0003_contribution_receipt_image_alter_contribution_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="display_name_choice",
            field=models.CharField(
                choices=[
                    ("hidden", "Hidden"),
                    ("display_name", "Display Name"),
                    ("full_name", "Full Name"),
                    ("custom", "Custom"),
                ],
                default="display_name",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="message",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="contribution",
            name="public_display_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="contribution",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="show_in_public_list",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
