# Generated by Django 5.2.15 on 2026-06-19 06:56

import random

from django.db import migrations, models


def backfill_tracking_codes(apps, schema_editor):
    Contribution = apps.get_model('fund', 'Contribution')
    existing = set(
        Contribution.objects.exclude(tracking_code__isnull=True)
        .exclude(tracking_code='')
        .values_list('tracking_code', flat=True)
    )
    for contribution in Contribution.objects.filter(
        models.Q(tracking_code__isnull=True) | models.Q(tracking_code='')
    ):
        for _ in range(20):
            candidate = f'FUND-{random.randint(100000, 999999)}'
            if candidate not in existing:
                existing.add(candidate)
                break
        else:
            raise RuntimeError('Could not generate a unique tracking code.')
        contribution.tracking_code = candidate
        contribution.save(update_fields=['tracking_code'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0004_contribution_display_name_choice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="tracking_code",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
        migrations.RunPython(backfill_tracking_codes, noop_reverse),
        migrations.AlterField(
            model_name="contribution",
            name="tracking_code",
            field=models.CharField(
                blank=True, editable=False, max_length=20, unique=True
            ),
        ),
    ]
