# Generated by Django 5.2.15 on 2026-06-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0006_contribution_tracking_code_reformat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="notes",
            field=models.TextField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="rejection_reason",
            field=models.TextField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.TextField(blank=True, max_length=550),
        ),
    ]
