# Generated by Django 5.2.15 on 2026-06-18 16:33

from django.db import migrations, models


def backfill_status(apps, schema_editor):
    Comment = apps.get_model('posts', 'Comment')
    Comment.objects.filter(is_approved=True).update(status='approved')
    Comment.objects.filter(is_approved=False).update(status='pending')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_comment_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_status, noop_reverse),
        migrations.RemoveField(
            model_name="comment",
            name="is_approved",
        ),
    ]
