# Generated by Django 5.2.15 on 2026-06-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_comment_tracking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="rejection_reason",
            field=models.TextField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=550),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(max_length=550),
        ),
    ]
