# Generated by Django 5.2.15 on 2026-06-05 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codename", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=350)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["codename"],
            },
        ),
    ]
