# Generated by Django 5.2.15 on 2026-06-19 09:07

import random

from django.db import migrations, models


def backfill_tracking_codes(apps, schema_editor):
    ContactMessage = apps.get_model('core', 'ContactMessage')
    existing = set(
        ContactMessage.objects.exclude(tracking_code__isnull=True)
        .exclude(tracking_code='')
        .values_list('tracking_code', flat=True)
    )
    for message in ContactMessage.objects.select_related('sender').filter(
        models.Q(tracking_code__isnull=True) | models.Q(tracking_code='')
    ):
        member_number = message.sender.member_number if message.sender_id else None
        prefix = f'{member_number:05d}' if member_number else '00000'
        for _ in range(20):
            candidate = f'{prefix}M{random.randint(0, 999):03d}'
            if candidate not in existing:
                existing.add(candidate)
                break
        else:
            raise RuntimeError('Could not generate a unique tracking code.')
        message.tracking_code = candidate
        message.save(update_fields=['tracking_code'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="tracking_code",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
        migrations.RunPython(backfill_tracking_codes, noop_reverse),
        migrations.AlterField(
            model_name="contactmessage",
            name="tracking_code",
            field=models.CharField(
                blank=True, editable=False, max_length=20, unique=True
            ),
        ),
    ]
