# Generated by Django 5.2.15 on 2026-06-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_contactmessage_tracking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name="defaultsetting",
            name="value",
            field=models.TextField(max_length=550),
        ),
    ]
